# Generated by Django 3.1.7 on 2023-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_type',
            field=models.CharField(choices=[('via_email', 'via_email'), ('via_phone', 'via_phone')], max_length=31),
        ),
    ]
